"""adjusted relationships - removed instructor relationships

Revision ID: 150ca5105bf0
Revises: 
Create Date: 2024-03-12 16:41:31.013700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '150ca5105bf0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instructors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('bio', sa.String(), nullable=False),
    sa.Column('experience', sa.Integer(), nullable=False),
    sa.Column('instrument', sa.String(), nullable=False),
    sa.Column('photo', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_instructors')),
    sa.UniqueConstraint('email', name=op.f('uq_instructors_email')),
    sa.UniqueConstraint('name', name=op.f('uq_instructors_name'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('primary_instrument', sa.String(), nullable=False),
    sa.Column('_password_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_table('lessons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_rating', sa.Boolean(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('instructor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['instructor_id'], ['instructors.id'], name=op.f('fk_lessons_instructor_id_instructors')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_lessons_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lessons'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lessons')
    op.drop_table('users')
    op.drop_table('instructors')
    # ### end Alembic commands ###
