"""adjusted constraints to instructor

Revision ID: 247a8fee8d31
Revises: 21b374137918
Create Date: 2024-03-13 21:46:35.963302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '247a8fee8d31'
down_revision = '21b374137918'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instructors', schema=None) as batch_op:
        batch_op.drop_constraint('uq_instructors_name', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instructors', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_instructors_name', ['name'])

    # ### end Alembic commands ###
